name: lirarate
description: A currency rate and fuel price provider.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.4
  html: ^0.15.0
  lottie: ^1.3.0
  flutter_spinkit: ^5.1.0
  get: ^4.6.5
  shared_preferences: ^2.0.15
  connectivity_plus: ^2.3.6
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - resources/animations/
    - resources/fonts/
  fonts:
    - family: Nunito
      fonts:
      - asset: resources/fonts/Nunito-Bold.ttf